In [3]:
# setup & config ---------------------------------------------------------
# (Lightkurve pulls Kepler data from MAST; requires internet at runtime.)

# !pip -q install lightkurve astroquery astropy pywavelets

import os
import math
import json
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (7, 4)
plt.rcParams["axes.grid"] = True

try:
    import lightkurve as lk
    from astropy.timeseries import BoxLeastSquares
except Exception as e:
    print("Note: lightkurve/astropy not imported yet. Install them if you plan to fetch from MAST.")
    print(e)

from matplotlib.animation import FuncAnimation, PillowWriter
from IPython.display import HTML

try:
    import pywt
except Exception as e:
    print("Scalogram (pywt) optional. Install pywavelets if you want it.")
    print(e)

data_path = "data/Kepler Object of Interest.xlsx"  # << change to your file
out_dir = Path("outputs")
out_dir.mkdir(exist_ok=True, parents=True)

TOP_N = 5

c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\prf\__init__.py:7: UserWarning: Warning: the tpfmodel submodule is not available without oktopus installed, which requires a current version of autograd. See #1452 for details.
  warnings.warn(

In [12]:
# fetch & preprocess light curves for koi

def fetch_pdcsap_lightcurve(kic_id: int, mission: str):
    """Download and return a stitched PDCSAP light curve for a given Kepler KIC ID."""
    try:
        sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission=mission)
        if len(sr) == 0:
            print(f"No LC files found for KIC {kic_id}.")
            return None
        lcf = sr.download_all()
        if lcf is None:
            print(f"Download failed for KIC {kic_id}.")
            return None
        lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
        lc = lc.flatten(window_length=401)
        return lc
    except Exception as e:
        print(f"Error fetching LC for KIC {kic_id}: {e}")
        return None

In [ ]:
# libraries
import pandas as pd

# create a json structure with two id fields 
kepid = [
  {"Kepid": 3118797, "KepoiName": "K01950.01"},
  {"Kepid": 4254466, "KepoiName": "K02134.01"},
  {"Kepid": 4914423, "KepoiName": "K00108.02"},
  {"Kepid": 6041734, "KepoiName": "K02167.01"},
  {"Kepid": 6047072, "KepoiName": "K02103.01"},
  {"Kepid": 6541920, "KepoiName": "K00157.06"},
  {"Kepid": 6665512, "KepoiName": "K02005.01"},
  {"Kepid": 7045496, "KepoiName": "K01939.01"},
  {"Kepid": 7094486, "KepoiName": "K01907.01"},
  {"Kepid": 7449541, "KepoiName": "K02063.01"},
  {"Kepid": 7620413, "KepoiName": "K02103.01"},
  {"Kepid": 7918992, "KepoiName": "K02095.01"},
  {"Kepid": 8081187, "KepoiName": "K01951.01"},
  {"Kepid": 8164012, "KepoiName": "K02116.01"},
  {"Kepid": 8233702, "KepoiName": "K02140.01"},
  {"Kepid": 8395660, "KepoiName": "K00116.02"},
  {"Kepid": 8559644, "KepoiName": "K00139.02"},
  {"Kepid": 8559644, "KepoiName": "K00139.01"},
  {"Kepid": 9006186, "KepoiName": "K02169.03"},
  {"Kepid": 9072190, "KepoiName": "K01933.01"},
  {"Kepid": 9205938, "KepoiName": "K02162.02"},
  {"Kepid": 9349482, "KepoiName": "K02020.01"},
  {"Kepid": 9353314, "KepoiName": "K01900.01"},
  {"Kepid": 9471974, "KepoiName": "K00119.01"},
  {"Kepid": 9473078, "KepoiName": "K02079.01"},
  {"Kepid": 9579641, "KepoiName": "K00115.01"},
  {"Kepid": 9790806, "KepoiName": "K02035.01"},
  {"Kepid": 10187017, "KepoiName": "K00082.04"},
  {"Kepid": 10190777, "KepoiName": "K01937.01"},
  {"Kepid": 10857519, "KepoiName": "K02075.01"},
  {"Kepid": 10875245, "KepoiName": "K00117.04"},
  {"Kepid": 10965588, "KepoiName": "K02177.01"},
  {"Kepid": 11086270, "KepoiName": "K00124.02"},
  {"Kepid": 11614617, "KepoiName": "K01990.01"},
  {"Kepid": 11923284, "KepoiName": "K02026.01"},
  {"Kepid": 12154526, "KepoiName": "K02004.01"}
]

# turn into a dataframe
kepid_df = pd.DataFrame(kepid)

# bring in the koi data
# slice the columns to kepid, kepoiname, koi_period, and koi_time0bk
koi_data_path = "data/Kepler Object of Interest.csv" 
koi_df = pd.read_csv(koi_data_path, usecols=["kepid", "kepoi_name", "koi_period", "koi_time0bk"])

# merge the two dataframes on kepoiname
enriched_koi_df = pd.merge(kepid_df, koi_df, left_on="KepoiName", right_on="kepoi_name", how="left")

# slice the columns to kepid, kepoiname, koi_period, and koi_time0bk
enriched_koi_df = enriched_koi_df[["kepid", "KepoiName", "koi_period", "koi_time0bk"]]
enriched_koi_df.head()

     kepid  KepoiName  koi_period  koi_time0bk
0  3118797  K01950.01   66.415979   188.139880
1  4254466  K02134.01   42.300628   168.777830
2  4914423  K00108.02  179.609803   295.330361
3  6041734  K02167.01   24.339820   136.058130
4  7620413  K02103.01    2.543064   132.681590

In [19]:
# tid 
tid = [
  {"TID": 351601843, "TOI": 1075.01},
  {"TID": 394561119, "TOI": 1107.01},
  {"TID": 52368076, "TOI": 125.02},
  {"TID": 355867695, "TOI": 1260.02},
  {"TID": 417948359, "TOI": 1272.01},
  {"TID": 89020549, "TOI": 132.01},
  {"TID": 62483237, "TOI": 139.01},
  {"TID": 428679607, "TOI": 1669.01},
  {"TID": 28900646, "TOI": 1685.01},
  {"TID": 183120439, "TOI": 169.01},
  {"TID": 233602827, "TOI": 1749.02},
  {"TID": 376524552, "TOI": 1811.01},
  {"TID": 404505029, "TOI": 1842.01},
  {"TID": 27491137, "TOI": 2076.01},
  {"TID": 441738827, "TOI": 2084.01},
  {"TID": 235678745, "TOI": 2095.02},
  {"TID": 392476080, "TOI": 2109.01},
  {"TID": 88992642, "TOI": 2145.01},
  {"TID": 395393265, "TOI": 2152.01},
  {"TID": 198485881, "TOI": 2257.01},
  {"TID": 24358417, "TOI": 2338.01},
  {"TID": 149845414, "TOI": 2545.01},
  {"TID": 348835438, "TOI": 2669.01},
  {"TID": 178162579, "TOI": 2842.01},
  {"TID": 361343239, "TOI": 2977.01},
  {"TID": 458419328, "TOI": 3785.01},
  {"TID": 95660472, "TOI": 3819.01},
  {"TID": 95057860, "TOI": 4201.01},
  {"TID": 144193715, "TOI": 4308.01},
  {"TID": 126606859, "TOI": 4479.01},
  {"TID": 49428710, "TOI": 5174.01},
  {"TID": 148673433, "TOI": 5704.01}
]

# turn into a dataframe
toi_df = pd.DataFrame(tid)

# bring in the tess data
tess_data_path = "data/TESS Project Candidates.csv"
tess_df = pd.read_csv(tess_data_path, usecols=["tid", "toi", "pl_orbper", "pl_tranmid"])

# merge the two dataframes on toi
enriched_tess_df = pd.merge(toi_df, tess_df, left_on="TOI", right_on="toi", how="left")

# slice the columns to kepid, kepoiname, koi_period, and koi_time0bk
enriched_tess_df = enriched_tess_df[["tid", "toi", "pl_orbper", "pl_tranmid"]]
enriched_tess_df.head()

         tid      toi  pl_orbper   pl_tranmid
0  351601843  1075.01   0.604739  2458654.250
1  394561119  1107.01   4.078239  2459336.074
2   52368076   125.02   9.154942  2460202.050
3  355867695  1260.02   7.493161  2458686.120
4  417948359  1272.01   3.315977  2459661.401

In [20]:
# view enriched df info
enriched_tess_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   tid         32 non-null     int64
 1   toi         32 non-null     float64
 2   pl_orbper   32 non-null     float64
 3   pl_tranmid  32 non-null     float64
dtypes: float64(3), int64(1)
memory usage: 1.1 KB

In [7]:
# --- deps ---
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from IPython.display import HTML, display
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
from matplotlib.animation import FuncAnimation, PillowWriter
import lightkurve as lk

# optional: where to save outputs
out_dir = Path("gifs/koi"); out_dir.mkdir(parents=True, exist_ok=True)

def fetch_pdcsap_lightcurve(kic_id: int):
    """Download and return a stitched, flattened PDCSAP light curve for a Kepler KIC ID."""
    try:
        sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
        if len(sr) == 0:
            print(f"No LC files found for KIC {kic_id}.")
            return None
        lcf = sr.download_all()
        if lcf is None:
            print(f"Download failed for KIC {kic_id}.")
            return None
        lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
        lc = lc.flatten(window_length=401)
        return lc
    except Exception as e:
        print(f"Error fetching LC for KIC {kic_id}: {e}")
        return None

def make_orbit_light_animation_3d(
    kic: int, lc, period: float, t0: float,
    frames: int = 300, orbit_radius: float = 3.0, save_path=None,
    rotate_camera=True, rot_per_anim=0.6, elev_deg=22,
    close_after=False
):
    """
    3D orbit (top) + measured PDCSAP flux vs phase (bottom), synchronized.
    """
    if lc is None:
        print("No light curve available for animation.")
        return None

    # --- Prepare arrays (plain floats, handle masked/quantities) ---
    t = np.asarray(getattr(lc.time, "value", lc.time), dtype=float)
    y = getattr(lc, "flux", None)
    if y is None:
        print("No flux in light curve.")
        return None
    y = getattr(y, "value", y)
    y = np.ma.getdata(y).astype(float, copy=False)

    # drop non-finite pairs up-front
    m = np.isfinite(t) & np.isfinite(y)
    t, y = t[m], y[m]

    if not np.isfinite(period) or period <= 0 or t.size < 10 or y.size < 10:
        print("Invalid LC/period for animation.")
        return None

    # normalize flux to ~1.0 median (helps alpha mapping)
    med = np.nanmedian(y)
    if np.isfinite(med) and med != 0:
        y = y / med

    # Phase-fold & sort for smooth traversal (BKJD compatible)
    t_rel = (t - float(t0)) % float(period)
    order = np.argsort(t_rel)
    t_rel, y = t_rel[order], y[order]
    if t_rel.size < 10:
        print("Too few samples to animate.")
        return None

    # Robust brightness -> alpha mapping
    finite_y = y[np.isfinite(y)]
    if finite_y.size < 10:
        print("Too few finite flux samples to animate.")
        return None
    q1, q2 = np.nanpercentile(finite_y, [1, 99])
    span = q2 - q1 if np.isfinite(q2 - q1) else 0.0

    def flux_to_alpha(f):
        if not np.isfinite(f) or span < 1e-8:
            return 1.0
        x = (float(f) - q1) / span
        return float(np.clip(0.3 + 0.7 * x, 0.0, 1.0))

    frames_eff = int(min(frames, max(20, t_rel.size)))

    # --- Figure layout (3D top + 2D bottom) ---
    fig = plt.figure(figsize=(7.2, 8.4))
    gs = fig.add_gridspec(2, 1, height_ratios=[2.0, 1.0])

    ax3d = fig.add_subplot(gs[0], projection='3d')
    axlc = fig.add_subplot(gs[1])

    # 3D orbit scaffolding
    th = np.linspace(0, 2*np.pi, 600)
    x_orb = orbit_radius*np.cos(th)
    y_orb = orbit_radius*np.sin(th)
    z_orb = np.zeros_like(th)
    ax3d.plot(x_orb, y_orb, z_orb, lw=1.5)

    # Star (scatter so we can set alpha dynamically)
    star = ax3d.scatter([0],[0],[0], s=600, alpha=1.0)

    # Planet marker (updated every frame)
    planet = ax3d.scatter([orbit_radius],[0],[0], s=60)

    # Nice view box
    lim = orbit_radius*1.25
    ax3d.set_xlim(-lim, lim); ax3d.set_ylim(-lim, lim); ax3d.set_zlim(-lim*0.2, lim*0.2)
    ax3d.set_xlabel("x"); ax3d.set_ylabel("y"); ax3d.set_zlabel("z")
    ax3d.set_title(f"KIC {kic} — schematic 3D orbit", pad=12)
    ax3d.view_init(elev=elev_deg, azim=45)

    # Flux plot
    axlc.plot(t_rel, y, lw=0.6)
    tracker = axlc.axvline(0.0, ls="--", lw=1.0)
    axlc.set_xlim(0, float(period))
    axlc.set_xlabel("Phase within period [days]")
    axlc.set_ylabel("Flux (normalized)")
    axlc.set_title("Measured flux vs phase (PDCSAP)")

    def update(i):
        # Index into folded series
        idx = int((i / max(1, (frames_eff - 1))) * (t_rel.size - 1))
        phase_now = float(t_rel[idx])
        angle = (phase_now / float(period)) * 2*np.pi

        # Planet position on circular orbit (in x–y plane)
        xp = orbit_radius*np.cos(angle)
        yp = orbit_radius*np.sin(angle)
        zp = 0.0

        # Update artists
        planet._offsets3d = ([xp], [yp], [zp])  # updating Path3DCollection
        tracker.set_xdata([phase_now, phase_now])

        # Star brightness follows flux
        a = flux_to_alpha(y[idx])
        star.set_alpha(a)

        # Optional camera rotation for depth perception
        if rotate_camera:
            az = 45 + 360*rot_per_anim*(i/frames_eff)
            ax3d.view_init(elev=elev_deg, azim=az)

        return planet, tracker, star

    anim = FuncAnimation(fig, update, frames=frames_eff, interval=35, blit=False)
    plt.tight_layout()

    if save_path:
        try:
            anim.save(save_path, writer=PillowWriter(fps=25))
            print("Saved animation:", save_path)
        except Exception as e:
            print("Could not save 3D animation. Error:", e)

    if close_after:
        plt.close(fig)

    return anim

In [8]:
# --- Example run for all KOIs in enriched_df ---
# enriched_df must contain: kepid, koi_period, koi_time0bk
if len(enriched_df) > 0:
    for i, row in enriched_df.iterrows():
        kic = int(row["kepid"])
        p = float(row["koi_period"])
        t0 = float(row["koi_time0bk"])

        lc = fetch_pdcsap_lightcurve(kic)
        print(f"Building 3D animation for KIC {kic} ({i+1}/{len(enriched_df)}) ...")
        gif3d_path = str((out_dir / f"{kic}.gif").resolve())

        anim3d = make_orbit_light_animation_3d(
            kic, lc, p, t0,
            frames=300,
            save_path=gif3d_path,
            close_after=True  # closes figure after saving to speed up loop
        )

        print(f"Saved GIF for KIC {kic} → {gif3d_path}")

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 3118797 (1/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\3118797.gif
Saved GIF for KIC 3118797 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\3118797.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 4254466 (2/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\4254466.gif
Saved GIF for KIC 4254466 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\4254466.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 4914423 (3/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\4914423.gif
Saved GIF for KIC 4914423 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\4914423.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 6041734 (4/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\6041734.gif
Saved GIF for KIC 6041734 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\6041734.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 7620413 (5/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7620413.gif
Saved GIF for KIC 7620413 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7620413.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
WARNING: File may have been truncated: actual file length (3211264) is smaller than the expected size (4443840) [astropy.io.fits.file]
WARNING: File may have been truncated: actual file length (3211264) is smaller than the expected size (4443840) [astropy.io.fits.file]
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")

Error fetching LC for KIC 6541920: Error in reading Data product C:\Users\roger\.lightkurve\cache\mastDownload\Kepler\kplr006541920_sc_Q000333333333333332\kplr006541920-2010265121752_slc.fits of type KeplerLightCurve .
This file may be corrupt due to an interrupted download. Please remove it from your disk and try again.
Building 3D animation for KIC 6541920 (6/36) ...
No light curve available for animation.
Saved GIF for KIC 6541920 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\6541920.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 6665512 (7/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\6665512.gif
Saved GIF for KIC 6665512 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\6665512.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 7045496 (8/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7045496.gif
Saved GIF for KIC 7045496 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7045496.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 7094486 (9/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7094486.gif
Saved GIF for KIC 7094486 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7094486.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 7449541 (10/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7449541.gif
Saved GIF for KIC 7449541 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7449541.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 7620413 (11/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7620413.gif
Saved GIF for KIC 7620413 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7620413.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 7918992 (12/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7918992.gif
Saved GIF for KIC 7918992 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\7918992.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 8081187 (13/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\8081187.gif
Saved GIF for KIC 8081187 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\8081187.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 8164012 (14/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\8164012.gif
Saved GIF for KIC 8164012 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\8164012.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 8233702 (15/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\8233702.gif
Saved GIF for KIC 8233702 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\8233702.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
WARNING: File may have been truncated: actual file length (1310720) is smaller than the expected size (4584960) [astropy.io.fits.file]
WARNING: File may have been truncated: actual file length (1310720) is smaller than the expected size (4584960) [astropy.io.fits.file]
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")

Error fetching LC for KIC 8395660: Error in reading Data product C:\Users\roger\.lightkurve\cache\mastDownload\Kepler\kplr008395660_sc_Q000333333333333332\kplr008395660-2011303113607_slc.fits of type KeplerLightCurve .
This file may be corrupt due to an interrupted download. Please remove it from your disk and try again.
Building 3D animation for KIC 8395660 (16/36) ...
No light curve available for animation.
Saved GIF for KIC 8395660 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\8395660.gif

WARNING: File may have been truncated: actual file length (327680) is smaller than the expected size (3836160) [astropy.io.fits.file]
WARNING: File may have been truncated: actual file length (327680) is smaller than the expected size (3836160) [astropy.io.fits.file]
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")

Error fetching LC for KIC 8559644: Error in reading Data product C:\Users\roger\.lightkurve\cache\mastDownload\Kepler\kplr008559644_sc_Q000333333333300010\kplr008559644-2009350160919_slc.fits of type KeplerLightCurve .
This file may be corrupt due to an interrupted download. Please remove it from your disk and try again.
Building 3D animation for KIC 8559644 (17/36) ...
No light curve available for animation.
Saved GIF for KIC 8559644 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\8559644.gif

WARNING: File may have been truncated: actual file length (327680) is smaller than the expected size (3836160) [astropy.io.fits.file]
WARNING: File may have been truncated: actual file length (327680) is smaller than the expected size (3836160) [astropy.io.fits.file]
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")

Error fetching LC for KIC 8559644: Error in reading Data product C:\Users\roger\.lightkurve\cache\mastDownload\Kepler\kplr008559644_sc_Q000333333333300010\kplr008559644-2009350160919_slc.fits of type KeplerLightCurve .
This file may be corrupt due to an interrupted download. Please remove it from your disk and try again.
Building 3D animation for KIC 8559644 (18/36) ...
No light curve available for animation.
Saved GIF for KIC 8559644 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\8559644.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 9006186 (19/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9006186.gif
Saved GIF for KIC 9006186 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9006186.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 9072190 (20/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9072190.gif
Saved GIF for KIC 9072190 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9072190.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 9205938 (21/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9205938.gif
Saved GIF for KIC 9205938 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9205938.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 9349482 (22/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9349482.gif
Saved GIF for KIC 9349482 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9349482.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 9353314 (23/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9353314.gif
Saved GIF for KIC 9353314 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9353314.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 9471974 (24/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9471974.gif
Saved GIF for KIC 9471974 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9471974.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 9473078 (25/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9473078.gif
Saved GIF for KIC 9473078 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9473078.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 9579641 (26/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9579641.gif
Saved GIF for KIC 9579641 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9579641.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 9790806 (27/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9790806.gif
Saved GIF for KIC 9790806 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\9790806.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 10187017 (28/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\10187017.gif
Saved GIF for KIC 10187017 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\10187017.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 10190777 (29/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\10190777.gif
Saved GIF for KIC 10190777 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\10190777.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 10857519 (30/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\10857519.gif
Saved GIF for KIC 10857519 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\10857519.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
WARNING: File may have been truncated: actual file length (3014656) is smaller than the expected size (5353920) [astropy.io.fits.file]
WARNING: File may have been truncated: actual file length (3014656) is smaller than the expected size (5353920) [astropy.io.fits.file]
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")

Error fetching LC for KIC 10875245: Error in reading Data product C:\Users\roger\.lightkurve\cache\mastDownload\Kepler\kplr010875245_sc_Q000333303330303032\kplr010875245-2013065031647_slc.fits of type KeplerLightCurve .
This file may be corrupt due to an interrupted download. Please remove it from your disk and try again.
Building 3D animation for KIC 10875245 (31/36) ...
No light curve available for animation.
Saved GIF for KIC 10875245 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\10875245.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 10965588 (32/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\10965588.gif
Saved GIF for KIC 10965588 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\10965588.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
WARNING: File may have been truncated: actual file length (1114112) is smaller than the expected size (4475520) [astropy.io.fits.file]
WARNING: File may have been truncated: actual file length (1114112) is smaller than the expected size (4475520) [astropy.io.fits.file]
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")

Error fetching LC for KIC 11086270: Error in reading Data product C:\Users\roger\.lightkurve\cache\mastDownload\Kepler\kplr011086270_sc_Q000333333330000001\kplr011086270-2009291181958_slc.fits of type KeplerLightCurve .
This file may be corrupt due to an interrupted download. Please remove it from your disk and try again.
Building 3D animation for KIC 11086270 (33/36) ...
No light curve available for animation.
Saved GIF for KIC 11086270 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11086270.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 11614617 (34/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11614617.gif
Saved GIF for KIC 11614617 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11614617.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 11923284 (35/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11923284.gif
Saved GIF for KIC 11923284 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11923284.gif

C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:16: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  sr = lk.search_lightcurvefile(f"KIC {kic_id}", mission="Kepler")
C:\Users\roger\AppData\Local\Temp\ipykernel_21840\3697049234.py:24: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc = lcf.PDCSAP_FLUX.stitch().remove_nans()
c:\Users\roger\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightkurve\collections.py:163: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  return LightCurveCollection([lc.PDCSAP_FLUX for lc in self])

Building 3D animation for KIC 12154526 (36/36) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12154526.gif
Saved GIF for KIC 12154526 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12154526.gif

In [26]:
# --- deps (unchanged) ---
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from IPython.display import HTML, display
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
from matplotlib.animation import FuncAnimation, PillowWriter
import lightkurve as lk

# optional: where to save outputs
out_dir = Path("gifs/tess"); out_dir.mkdir(parents=True, exist_ok=True)

def fetch_pdcsap_lightcurve(tic_id: int):
    """Download & return a stitched, normalized, flattened TESS light curve for a TIC ID.
    Tries SPOC/QLP across common cadences; falls back to any author; then TESSCut FFIs.
    """
    try:
        # Try common authors and cadences first
        for author in ("SPOC", "QLP"):
            # None means "any cadence"; otherwise try specific exptimes too
            for exptime in (20, 120, 600, 1800, None):
                sr = lk.search_lightcurve(f"TIC {tic_id}", mission="TESS",
                                          author=author, exptime=exptime)
                if len(sr) == 0:
                    continue
                lc_col = sr.download_all()
                if lc_col is None or len(lc_col) == 0:
                    continue
                lc = lc_col.stitch().remove_nans().normalize().flatten(window_length=401)
                return lc

        # Fallback: any author/cadence
        sr_any = lk.search_lightcurve(f"TIC {tic_id}", mission="TESS")
        if len(sr_any) > 0:
            lc_col = sr_any.download_all()
            if lc_col is not None and len(lc_col) > 0:
                lc = lc_col.stitch().remove_nans().normalize().flatten(window_length=401)
                return lc

        # Last resort: TESSCut (FFI cutouts → light curve)
        sr_cut = lk.search_tesscut(f"TIC {tic_id}")
        if len(sr_cut) > 0:
            # Download first available sector cutout and extract LC
            tpf = sr_cut[0].download(cutout_size=15)
            if tpf is not None:
                lc = (tpf.to_lightcurve(aperture_mask="pipeline")
                          .remove_nans().normalize().flatten(window_length=401))
                return lc

        print(f"No usable TESS light curve found for TIC {tic_id} (SPOC, QLP, any, TESSCut).")
        return None
    except Exception as e:
        print(f"Error fetching LC for TIC {tic_id}: {e}")
        return None


def make_orbit_light_animation_3d(
    kic: int, lc, period: float, t0: float,
    frames: int = 300, orbit_radius: float = 3.0, save_path=None,
    rotate_camera=True, rot_per_anim=0.6, elev_deg=22,
    close_after=False
):
    """
    3D orbit (top) + measured PDCSAP flux vs phase (bottom), synchronized.
    """
    if lc is None:
        print("No light curve available for animation.")
        return None

    # --- Prepare arrays (plain floats, handle masked/quantities) ---
    t = np.asarray(getattr(lc.time, "value", lc.time), dtype=float)
    y = getattr(lc, "flux", None)
    if y is None:
        print("No flux in light curve.")
        return None
    y = getattr(y, "value", y)
    y = np.ma.getdata(y).astype(float, copy=False)

    # drop non-finite pairs up-front
    m = np.isfinite(t) & np.isfinite(y)
    t, y = t[m], y[m]

    if not np.isfinite(period) or period <= 0 or t.size < 10 or y.size < 10:
        print("Invalid LC/period for animation.")
        return None

    # normalize flux to ~1.0 median (helps alpha mapping)
    med = np.nanmedian(y)
    if np.isfinite(med) and med != 0:
        y = y / med

    # Phase-fold & sort for smooth traversal (BKJD compatible)
    t_rel = (t - float(t0)) % float(period)
    order = np.argsort(t_rel)
    t_rel, y = t_rel[order], y[order]
    if t_rel.size < 10:
        print("Too few samples to animate.")
        return None

    # Robust brightness -> alpha mapping
    finite_y = y[np.isfinite(y)]
    if finite_y.size < 10:
        print("Too few finite flux samples to animate.")
        return None
    q1, q2 = np.nanpercentile(finite_y, [1, 99])
    span = q2 - q1 if np.isfinite(q2 - q1) else 0.0

    def flux_to_alpha(f):
        if not np.isfinite(f) or span < 1e-8:
            return 1.0
        x = (float(f) - q1) / span
        return float(np.clip(0.3 + 0.7 * x, 0.0, 1.0))

    frames_eff = int(min(frames, max(20, t_rel.size)))

    # --- Figure layout (3D top + 2D bottom) ---
    fig = plt.figure(figsize=(7.2, 8.4))
    gs = fig.add_gridspec(2, 1, height_ratios=[2.0, 1.0])

    ax3d = fig.add_subplot(gs[0], projection='3d')
    axlc = fig.add_subplot(gs[1])

    # 3D orbit scaffolding
    th = np.linspace(0, 2*np.pi, 600)
    x_orb = orbit_radius*np.cos(th)
    y_orb = orbit_radius*np.sin(th)
    z_orb = np.zeros_like(th)
    ax3d.plot(x_orb, y_orb, z_orb, lw=1.5)

    # Star (scatter so we can set alpha dynamically)
    star = ax3d.scatter([0],[0],[0], s=600, alpha=1.0)

    # Planet marker (updated every frame)
    planet = ax3d.scatter([orbit_radius],[0],[0], s=60)

    # Nice view box
    lim = orbit_radius*1.25
    ax3d.set_xlim(-lim, lim); ax3d.set_ylim(-lim, lim); ax3d.set_zlim(-lim*0.2, lim*0.2)
    ax3d.set_xlabel("x"); ax3d.set_ylabel("y"); ax3d.set_zlabel("z")
    ax3d.set_title(f"TIC {kic} — schematic 3D orbit", pad=12)
    ax3d.view_init(elev=elev_deg, azim=45)

    # Flux plot
    axlc.plot(t_rel, y, lw=0.6)
    tracker = axlc.axvline(0.0, ls="--", lw=1.0)
    axlc.set_xlim(0, float(period))
    axlc.set_xlabel("Phase within period [days]")
    axlc.set_ylabel("Flux (normalized)")
    axlc.set_title("Measured flux vs phase (PDCSAP)")

    def update(i):
        # Index into folded series
        idx = int((i / max(1, (frames_eff - 1))) * (t_rel.size - 1))
        phase_now = float(t_rel[idx])
        angle = (phase_now / float(period)) * 2*np.pi

        # Planet position on circular orbit (in x–y plane)
        xp = orbit_radius*np.cos(angle)
        yp = orbit_radius*np.sin(angle)
        zp = 0.0

        # Update artists
        planet._offsets3d = ([xp], [yp], [zp])  # updating Path3DCollection
        tracker.set_xdata([phase_now, phase_now])

        # Star brightness follows flux
        a = flux_to_alpha(y[idx])
        star.set_alpha(a)

        # Optional camera rotation for depth perception
        if rotate_camera:
            az = 45 + 360*rot_per_anim*(i/frames_eff)
            ax3d.view_init(elev=elev_deg, azim=az)

        return planet, tracker, star

    anim = FuncAnimation(fig, update, frames=frames_eff, interval=35, blit=False)
    plt.tight_layout()

    if save_path:
        try:
            anim.save(save_path, writer=PillowWriter(fps=25))
            print("Saved animation:", save_path)
        except Exception as e:
            print("Could not save 3D animation. Error:", e)

    if close_after:
        plt.close(fig)

    return anim

In [27]:
# enriched_tess_df must contain: tid (TIC), pl_orbper [days], pl_tranmid [BJD_TDB]
if len(enriched_tess_df) > 0:
    for i, row in enriched_tess_df.iterrows():
        tic = int(row["tid"])
        P   = float(row["pl_orbper"])
        t0_bjd = float(row["pl_tranmid"])     # BJD_TDB from your table

        # TESS light curve time is BTJD = BJD_TDB - 2457000
        t0_btjd = t0_bjd - 2457000.0

        lc = fetch_pdcsap_lightcurve(tic)
        if lc is None:
            print(f"Skipping TIC {tic} (no LC).")
            continue

        print(f"Building 3D animation for TIC {tic} ({i+1}/{len(enriched_tess_df)}) ...")
        gif3d_path = str((out_dir / f"{tic}.gif").resolve())

        anim3d = make_orbit_light_animation_3d(
            tic, lc, P, t0_btjd,   # pass BTJD epoch for TESS data
            frames=300,
            save_path=gif3d_path,
            close_after=True
        )

        print(f"Saved GIF for TIC {tic} → {gif3d_path}")

Building 3D animation for TIC 351601843 (1/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\351601843.gif
Saved GIF for TIC 351601843 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\351601843.gif
Building 3D animation for TIC 394561119 (2/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\394561119.gif
Saved GIF for TIC 394561119 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\394561119.gif
Building 3D animation for TIC 52368076 (3/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\52368076.gif
Saved GIF for TIC 52368076 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\52368076.gif
Building 3D animation for TIC 355867695 (4/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\355867695.gif
Saved GIF for TIC 355867695 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\355867695.gif

Warning: 24% (4649/19050) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

Building 3D animation for TIC 417948359 (5/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\417948359.gif
Saved GIF for TIC 417948359 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\417948359.gif
Building 3D animation for TIC 89020549 (6/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\89020549.gif
Saved GIF for TIC 89020549 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\89020549.gif
Building 3D animation for TIC 62483237 (7/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\62483237.gif
Saved GIF for TIC 62483237 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\62483237.gif
Building 3D animation for TIC 428679607 (8/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\428679607.gif
Saved GIF for TIC 428679607 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\428679607.gif
Building 3D animation for TIC 28900646 (9/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\28900646.gif
Saved GIF for TIC 28900646 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\28900646.gif
Building 3D animation for TIC 183120439 (10/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\183120439.gif
Saved GIF for TIC 183120439 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\183120439.gif
Building 3D animation for TIC 233602827 (11/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\233602827.gif
Saved GIF for TIC 233602827 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\233602827.gif
Building 3D animation for TIC 376524552 (12/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\376524552.gif
Saved GIF for TIC 376524552 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\376524552.gif

Warning: 22% (3972/18126) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

Building 3D animation for TIC 404505029 (13/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\404505029.gif
Saved GIF for TIC 404505029 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\404505029.gif

Warning: 20% (21755/108769) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
Warning: 26% (20345/77432) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

Building 3D animation for TIC 27491137 (14/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\27491137.gif
Saved GIF for TIC 27491137 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\27491137.gif
Building 3D animation for TIC 441738827 (15/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\441738827.gif
Saved GIF for TIC 441738827 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\441738827.gif
Building 3D animation for TIC 235678745 (16/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\235678745.gif
Saved GIF for TIC 235678745 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\235678745.gif
Building 3D animation for TIC 392476080 (17/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\392476080.gif
Saved GIF for TIC 392476080 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\392476080.gif
Building 3D animation for TIC 88992642 (18/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\88992642.gif
Saved GIF for TIC 88992642 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\88992642.gif
Building 3D animation for TIC 395393265 (19/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\395393265.gif
Saved GIF for TIC 395393265 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\395393265.gif
Building 3D animation for TIC 198485881 (20/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\198485881.gif
Saved GIF for TIC 198485881 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\198485881.gif
Building 3D animation for TIC 24358417 (21/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\24358417.gif
Saved GIF for TIC 24358417 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\24358417.gif
Building 3D animation for TIC 149845414 (22/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\149845414.gif
Saved GIF for TIC 149845414 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\149845414.gif
Building 3D animation for TIC 348835438 (23/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\348835438.gif
Saved GIF for TIC 348835438 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\348835438.gif
Building 3D animation for TIC 178162579 (24/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\178162579.gif
Saved GIF for TIC 178162579 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\178162579.gif
Building 3D animation for TIC 361343239 (25/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\361343239.gif
Saved GIF for TIC 361343239 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\361343239.gif
Building 3D animation for TIC 458419328 (26/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\458419328.gif
Saved GIF for TIC 458419328 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\458419328.gif
Building 3D animation for TIC 95660472 (27/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\95660472.gif
Saved GIF for TIC 95660472 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\95660472.gif
Building 3D animation for TIC 95057860 (28/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\95057860.gif
Saved GIF for TIC 95057860 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\95057860.gif
Building 3D animation for TIC 144193715 (29/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\144193715.gif
Saved GIF for TIC 144193715 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\144193715.gif
Building 3D animation for TIC 126606859 (30/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\126606859.gif
Saved GIF for TIC 126606859 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\126606859.gif
Building 3D animation for TIC 49428710 (31/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\49428710.gif
Saved GIF for TIC 49428710 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\49428710.gif
Building 3D animation for TIC 148673433 (32/32) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\148673433.gif
Saved GIF for TIC 148673433 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\148673433.gif

In [19]:
exoid = [
  {"Source": "TESS", "TID/KEPID": 8260536, "TOI/KOI": "5398.01"},
  {"Source": "KOI", "TID/KEPID": 12785320, "TOI/KOI": "K00298.01"},
  {"Source": "TESS", "TID/KEPID": 219016883, "TOI/KOI": "5238.01"},
  {"Source": "KOI", "TID/KEPID": 12644822, "TOI/KOI": "K00791.01"},
  {"Source": "TESS", "TID/KEPID": 100389539, "TOI/KOI": "4791.01"},
  {"Source": "KOI", "TID/KEPID": 12404305, "TOI/KOI": "K00486.01"},
  {"Source": "TESS", "TID/KEPID": 437856897, "TOI/KOI": "4603.01"},
  {"Source": "KOI", "TID/KEPID": 12400538, "TOI/KOI": "K01503.01"},
  {"Source": "TESS", "TID/KEPID": 232608943, "TOI/KOI": "4600.02"},
  {"Source": "KOI", "TID/KEPID": 12206313, "TOI/KOI": "K02714.01"},
  {"Source": "TESS", "TID/KEPID": 354944123, "TOI/KOI": "4342.02"},
  {"Source": "KOI", "TID/KEPID": 12120307, "TOI/KOI": "K02597.01"},
  {"Source": "TESS", "TID/KEPID": 256722647, "TOI/KOI": "4329.01"},
  {"Source": "KOI", "TID/KEPID": 12068975, "TOI/KOI": "K00623.03"},
  {"Source": "TESS", "TID/KEPID": 257060897, "TOI/KOI": "4138.01"},
  {"Source": "KOI", "TID/KEPID": 12061969, "TOI/KOI": "K02061.02"},
  {"Source": "TESS", "TID/KEPID": 289661991, "TOI/KOI": "3807.01"},
  {"Source": "KOI", "TID/KEPID": 12058931, "TOI/KOI": "K00546.02"},
  {"Source": "TESS", "TID/KEPID": 17865622, "TOI/KOI": "3540.01"},
  {"Source": "KOI", "TID/KEPID": 12058204, "TOI/KOI": "K02218.02"},
  {"Source": "TESS", "TID/KEPID": 428699140, "TOI/KOI": "3082.01"},
  {"Source": "KOI", "TID/KEPID": 12058147, "TOI/KOI": "K02072.01"},
  {"Source": "TESS", "TID/KEPID": 361343239, "TOI/KOI": "2977.01"},
  {"Source": "KOI", "TID/KEPID": 11963206, "TOI/KOI": "K02820.01"},
  {"Source": "TESS", "TID/KEPID": 178162579, "TOI/KOI": "2842.01"},
  {"Source": "KOI", "TID/KEPID": 11853878, "TOI/KOI": "K01833.03"},
  {"Source": "TESS", "TID/KEPID": 220076110, "TOI/KOI": "2796.01"},
  {"Source": "KOI", "TID/KEPID": 11807274, "TOI/KOI": "K00262.01"},
  {"Source": "TESS", "TID/KEPID": 258920431, "TOI/KOI": "2567.01"},
  {"Source": "KOI", "TID/KEPID": 11764462, "TOI/KOI": "K01531.01"},
  {"Source": "KOI", "TID/KEPID": 11754553, "TOI/KOI": "K00775.03"},
  {"Source": "KOI", "TID/KEPID": 11720424, "TOI/KOI": "K03116.01"},
  {"Source": "KOI", "TID/KEPID": 11718144, "TOI/KOI": "K02310.01"},
  {"Source": "KOI", "TID/KEPID": 11656918, "TOI/KOI": "K01945.01"},
  {"Source": "KOI", "TID/KEPID": 11656246, "TOI/KOI": "K01532.01"}
]

# turn into a dataframe
exo_df = pd.DataFrame(exoid)

# bring in the koi data
exo_koi_data_path = "data/Kepler Object of Interest.csv"
exo_koi_df = pd.read_csv(exo_koi_data_path, usecols=["kepid", "kepoi_name", "koi_period", "koi_time0bk"])

# bring in the tess data
exo_tess_data_path = "data/TESS Project Candidates.csv"
exo_tess_df = pd.read_csv(exo_tess_data_path, usecols=["tid", "toi", "pl_orbper", "pl_tranmid"])

# rename both exo dfs to union on koi/toi
exo_koi_df = exo_koi_df.rename(columns={
    "kepid": "ID",
    "kepoi_name": "EXOName",
    "koi_period": "Period",
    "koi_time0bk": "Epoch"
})  

exo_tess_df = exo_tess_df.rename(columns={
    "tid": "ID",  
    "toi": "EXOName",
    "pl_orbper": "Period",
    "pl_tranmid": "Epoch"
})  

# turn EXOName in exo_tess_df to string type
exo_tess_df["EXOName"] = exo_tess_df["EXOName"].astype(str)

# union both dataframes
enriched_exo_df = pd.concat([exo_koi_df, exo_tess_df], ignore_index=True) 

# join with exoid on ID and EXOName
enriched_exo_df = pd.merge(exo_df, enriched_exo_df, left_on=["TID/KEPID", "TOI/KOI"], right_on=["ID", "EXOName"], how="left")

# slice the columns to TID, EXOName, Period, and Epoch
enriched_exo_df = enriched_exo_df[["Source", "TID/KEPID", "EXOName", "Period", "Epoch"]]

enriched_exo_df

   Source  TID/KEPID    EXOName      Period         Epoch
0    TESS    8260536    5398.01   10.590923  2.459616e+06
1     KOI   12785320  K00298.01   19.963672  1.783081e+02
2    TESS  219016883    5238.01    4.872190  2.459662e+06
3     KOI   12644822  K00791.01   12.611904  1.808923e+02
4    TESS  100389539    4791.01    4.280977  2.459246e+06
5     KOI   12404305  K00486.01   22.183323  1.694962e+02
6    TESS  437856897    4603.01    7.245600  2.460274e+06
7     KOI   12400538  K01503.01  150.241258  1.382901e+02
8    TESS  232608943    4600.02  482.819100  2.459752e+06
9     KOI   12206313  K02714.01   14.383227  1.405765e+02
10   TESS  354944123    4342.02   10.688608  2.458659e+06
11    KOI   12120307  K02597.01    8.005047  1.387123e+02
12   TESS  256722647    4329.01    2.922466  2.459855e+06
13    KOI   12068975  K00623.03    5.599315  1.714739e+02
14   TESS  257060897    4138.01    3.660032  2.459661e+06
15    KOI   12061969  K02061.02    1.090011  1.315807e+02
16   TESS  289661991    3807.01    2.898976  2.459937e+06
17    KOI   12058931  K00546.02    9.825785  1.314249e+02
18   TESS   17865622    3540.01    3.119840  2.459827e+06
19    KOI   12058204  K02218.02   16.726197  1.437467e+02
20   TESS  428699140    3082.01    1.926804  2.459332e+06
21    KOI   12058147  K02072.01    1.543205  1.315554e+02
22   TESS  361343239    2977.01    2.350570  2.459332e+06
23    KOI   11963206  K02820.01    3.009125  1.316270e+02
24   TESS  178162579    2842.01    3.551402  2.459225e+06
25    KOI   11853878  K01833.03    5.709408  1.371221e+02
26   TESS  220076110    2796.01    4.808498  2.459190e+06
27    KOI   11807274  K00262.01    7.812859  1.726138e+02
28   TESS  258920431    2567.01    5.983945  2.459391e+06
29    KOI   11764462  K01531.01    5.699196  1.365874e+02
30    KOI   11754553  K00775.03   36.445400  1.516012e+02
31    KOI   11720424  K03116.01   23.910706  1.505394e+02
32    KOI   11718144  K02310.01   16.458186  1.340197e+02
33    KOI   11656918  K01945.01   62.138598  1.611483e+02
34    KOI   11656246  K01532.01   18.114738  1.474904e+02

In [16]:
# view enriched df info
enriched_exo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TID/KEPID  35 non-null     int64
 1   EXOName    35 non-null     object
 2   Period     35 non-null     float64
 3   Epoch      35 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 1.2+ KB

In [17]:
# view 
exo_koi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       9564 non-null   int64
 1   EXOName  9564 non-null   object
 2   Period   9564 non-null   float64
 3   Epoch    9564 non-null   float64
dtypes: float64(2), int64(1), object(1)
memory usage: 299.0+ KB

In [18]:
# view 
exo_tess_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7703 entries, 0 to 7702
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   EXOName  7703 non-null   object
 1   ID       7703 non-null   int64
 2   Epoch    7703 non-null   float64
 3   Period   7596 non-null   float64
dtypes: float64(2), int64(1), object(1)
memory usage: 240.8+ KB

In [ ]:
# --- deps (unchanged) ---
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from IPython.display import HTML, display
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
from matplotlib.animation import FuncAnimation, PillowWriter
import lightkurve as lk

# Prepare both output roots (we'll choose per-row in your loop)
Path("gifs/tess").mkdir(parents=True, exist_ok=True)
Path("gifs/koi").mkdir(parents=True, exist_ok=True)

def fetch_pdcsap_lightcurve(tic_id: int):
    """Download & return a stitched, normalized, flattened TESS light curve for a TIC ID.
    Tries SPOC/QLP across common cadences; falls back to any author; then TESSCut FFIs.
    """
    try:
        # Try common authors and cadences first
        for author in ("SPOC", "QLP"):
            # None means "any cadence"; otherwise try specific exptimes too
            for exptime in (20, 120, 600, 1800, None):
                sr = lk.search_lightcurve(f"TIC {tic_id}", mission="TESS",
                                          author=author, exptime=exptime)
                if len(sr) == 0:
                    continue
                lc_col = sr.download_all()
                if lc_col is None or len(lc_col) == 0:
                    continue
                lc = lc_col.stitch().remove_nans().normalize().flatten(window_length=401)
                return lc

        # Fallback: any author/cadence
        sr_any = lk.search_lightcurve(f"TIC {tic_id}", mission="TESS")
        if len(sr_any) > 0:
            lc_col = sr_any.download_all()
            if lc_col is not None and len(lc_col) > 0:
                lc = lc_col.stitch().remove_nans().normalize().flatten(window_length=401)
                return lc

        # Last resort: TESSCut (FFI cutouts → light curve)
        sr_cut = lk.search_tesscut(f"TIC {tic_id}")
        if len(sr_cut) > 0:
            # Download first available sector cutout and extract LC
            tpf = sr_cut[0].download(cutout_size=15)
            if tpf is not None:
                lc = (tpf.to_lightcurve(aperture_mask="pipeline")
                          .remove_nans().normalize().flatten(window_length=401))
                return lc

        print(f"No usable TESS light curve found for TIC {tic_id} (SPOC, QLP, any, TESSCut).")
        return None
    except Exception as e:
        print(f"Error fetching LC for TIC {tic_id}: {e}")
        return None


def fetch_kepler_lightcurve(kic_id: int):
    """Download & return a stitched, normalized, flattened Kepler light curve for a KIC ID."""
    try:
        # Try canonical Kepler cadences; fall back to "any"
        for exptime in (60, 1800, None):  # short, long, any
            sr = lk.search_lightcurve(f"KIC {kic_id}", mission="Kepler", exptime=exptime)
            if len(sr) == 0:
                continue
            lc_col = sr.download_all()
            if lc_col is None or len(lc_col) == 0:
                continue
            lc = lc_col.stitch().remove_nans().normalize().flatten(window_length=401)
            return lc

        # As a final fallback, try without exptime constraint
        sr_any = lk.search_lightcurve(f"KIC {kic_id}", mission="Kepler")
        if len(sr_any) > 0:
            lc_col = sr_any.download_all()
            if lc_col is not None and len(lc_col) > 0:
                lc = lc_col.stitch().remove_nans().normalize().flatten(window_length=401)
                return lc

        print(f"No usable Kepler light curve found for KIC {kic_id}.")
        return None
    except Exception as e:
        print(f"Error fetching LC for KIC {kic_id}: {e}")
        return None


def make_orbit_light_animation_3d(
    target_id: int, lc, period: float, t0: float,
    frames: int = 300, orbit_radius: float = 3.0, save_path=None,
    rotate_camera=True, rot_per_anim=0.6, elev_deg=22,
    close_after=False, id_label: str = "TIC"
):
    """
    3D orbit (top) + measured PDCSAP/SAP flux vs phase (bottom), synchronized.
    Pass an epoch (t0) already expressed in the mission's time base:
      - TESS: BTJD (BJD_TDB - 2457000)
      - Kepler: BKJD (BJD_TDB - 2454833)
    """
    if lc is None:
        print("No light curve available for animation.")
        return None

    # --- Prepare arrays (plain floats, handle masked/quantities) ---
    t = np.asarray(getattr(lc.time, "value", lc.time), dtype=float)
    y = getattr(lc, "flux", None)
    if y is None:
        print("No flux in light curve.")
        return None
    y = getattr(y, "value", y)
    y = np.ma.getdata(y).astype(float, copy=False)

    # drop non-finite pairs up-front
    m = np.isfinite(t) & np.isfinite(y)
    t, y = t[m], y[m]

    if not np.isfinite(period) or period <= 0 or t.size < 10 or y.size < 10:
        print("Invalid LC/period for animation.")
        return None

    # normalize flux to ~1.0 median (helps alpha mapping)
    med = np.nanmedian(y)
    if np.isfinite(med) and med != 0:
        y = y / med

    # Phase-fold & sort for smooth traversal (epoch already in correct time base)
    t_rel = (t - float(t0)) % float(period)
    order = np.argsort(t_rel)
    t_rel, y = t_rel[order], y[order]
    if t_rel.size < 10:
        print("Too few samples to animate.")
        return None

    # Robust brightness -> alpha mapping
    finite_y = y[np.isfinite(y)]
    if finite_y.size < 10:
        print("Too few finite flux samples to animate.")
        return None
    q1, q2 = np.nanpercentile(finite_y, [1, 99])
    span = q2 - q1 if np.isfinite(q2 - q1) else 0.0

    def flux_to_alpha(f):
        if not np.isfinite(f) or span < 1e-8:
            return 1.0
        x = (float(f) - q1) / span
        return float(np.clip(0.3 + 0.7 * x, 0.0, 1.0))

    frames_eff = int(min(frames, max(20, t_rel.size)))

    # --- Figure layout (3D top + 2D bottom) ---
    fig = plt.figure(figsize=(7.2, 8.4))
    gs = fig.add_gridspec(2, 1, height_ratios=[2.0, 1.0])

    ax3d = fig.add_subplot(gs[0], projection='3d')
    axlc = fig.add_subplot(gs[1])

    # 3D orbit scaffolding
    th = np.linspace(0, 2*np.pi, 600)
    x_orb = orbit_radius*np.cos(th)
    y_orb = orbit_radius*np.sin(th)
    z_orb = np.zeros_like(th)
    ax3d.plot(x_orb, y_orb, z_orb, lw=1.5)

    # Star (scatter so we can set alpha dynamically)
    star = ax3d.scatter([0],[0],[0], s=600, alpha=1.0)

    # Planet marker (updated every frame)
    planet = ax3d.scatter([orbit_radius],[0],[0], s=60)

    # Nice view box
    lim = orbit_radius*1.25
    ax3d.set_xlim(-lim, lim); ax3d.set_ylim(-lim, lim); ax3d.set_zlim(-lim*0.2, lim*0.2)
    ax3d.set_xlabel("x"); ax3d.set_ylabel("y"); ax3d.set_zlabel("z")
    ax3d.set_title(f"{id_label} {target_id} — schematic 3D orbit", pad=12)
    ax3d.view_init(elev=elev_deg, azim=45)

    # Flux plot
    axlc.plot(t_rel, y, lw=0.6)
    tracker = axlc.axvline(0.0, ls="--", lw=1.0)
    axlc.set_xlim(0, float(period))
    axlc.set_xlabel("Phase within period [days]")
    axlc.set_ylabel("Flux (normalized)")
    axlc.set_title("Measured flux vs phase")

    def update(i):
        # Index into folded series
        idx = int((i / max(1, (frames_eff - 1))) * (t_rel.size - 1))
        phase_now = float(t_rel[idx])
        angle = (phase_now / float(period)) * 2*np.pi

        # Planet position on circular orbit (in x–y plane)
        xp = orbit_radius*np.cos(angle)
        yp = orbit_radius*np.sin(angle)
        zp = 0.0

        # Update artists
        planet._offsets3d = ([xp], [yp], [zp])  # updating Path3DCollection
        tracker.set_xdata([phase_now, phase_now])

        # Star brightness follows flux
        a = flux_to_alpha(y[idx])
        star.set_alpha(a)

        # Optional camera rotation for depth perception
        if rotate_camera:
            az = 45 + 360*rot_per_anim*(i/frames_eff)
            ax3d.view_init(elev=elev_deg, azim=az)

        return planet, tracker, star

    anim = FuncAnimation(fig, update, frames=frames_eff, interval=35, blit=False)
    plt.tight_layout()

    if save_path:
        try:
            anim.save(save_path, writer=PillowWriter(fps=25))
            print("Saved animation:", save_path)
        except Exception as e:
            print("Could not save 3D animation. Error:", e)

    if close_after:
        plt.close(fig)

    return anim

In [23]:
# enriched_exo_df must contain: Source, TID/KEPID, Period [days], Epoch
# (Epoch time base: TESS= BJD_TDB → convert to BTJD; KOI/Kepler = BKJD already)
from pathlib import Path
import pandas as pd

tess_dir = Path("gifs/tess"); tess_dir.mkdir(parents=True, exist_ok=True)
koi_dir  = Path("gifs/koi");  koi_dir.mkdir(parents=True, exist_ok=True)

if len(enriched_exo_df) > 0:
    for i, row in enriched_exo_df.iterrows():
        src = str(row["Source"]).strip().upper()

        # basic parsing/sanity
        try:
            obj_id = int(row["TID/KEPID"])
            P      = float(row["Period"])
            t0     = float(row["Epoch"])
        except Exception:
            print(f"Skipping row {i}: non-numeric ID/Period/Epoch.")
            continue
        if P <= 0:
            print(f"Skipping row {i}: invalid period {P}.")
            continue

        if src == "TESS":
            # TESS: convert BJD_TDB epoch → BTJD
            t0_pass = t0 - 2457000.0
            lc = fetch_pdcsap_lightcurve(obj_id)
            out_dir = tess_dir
            id_label = "TIC"
            fname = f"{obj_id}.gif"
        elif src == "KOI":
            # Kepler/KOI: koi_time0bk is already BKJD
            t0_pass = t0
            lc = fetch_kepler_lightcurve(obj_id)
            out_dir = koi_dir
            id_label = "KIC"
            fname = f"{obj_id}.gif"
        else:
            print(f"Skipping row {i}: unknown Source '{row['Source']}'.")
            continue

        if lc is None:
            print(f"Skipping {id_label} {obj_id} (no LC).")
            continue

        print(f"Building 3D animation for {id_label} {obj_id} ({i+1}/{len(enriched_exo_df)}) ...")
        gif3d_path = str((out_dir / fname).resolve())

        anim3d = make_orbit_light_animation_3d(
            obj_id, lc, P, t0_pass,             # pass mission-appropriate epoch
            frames=300,
            save_path=gif3d_path,
            close_after=True,
            id_label=id_label
        )

        if anim3d is not None:
            print(f"Saved GIF for {id_label} {obj_id} → {gif3d_path}")

Building 3D animation for TIC 8260536 (1/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\8260536.gif
Saved GIF for TIC 8260536 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\8260536.gif
Building 3D animation for KIC 12785320 (2/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12785320.gif
Saved GIF for KIC 12785320 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12785320.gif
Building 3D animation for TIC 219016883 (3/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\219016883.gif
Saved GIF for TIC 219016883 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\219016883.gif
Building 3D animation for KIC 12644822 (4/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12644822.gif
Saved GIF for KIC 12644822 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12644822.gif
Building 3D animation for TIC 100389539 (5/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\100389539.gif
Saved GIF for TIC 100389539 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\100389539.gif
Building 3D animation for KIC 12404305 (6/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12404305.gif
Saved GIF for KIC 12404305 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12404305.gif
Building 3D animation for TIC 437856897 (7/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\437856897.gif
Saved GIF for TIC 437856897 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\437856897.gif
Building 3D animation for KIC 12400538 (8/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12400538.gif
Saved GIF for KIC 12400538 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12400538.gif
Error fetching LC for TIC 232608943: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Skipping TIC 232608943 (no LC).
Building 3D animation for KIC 12206313 (10/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12206313.gif
Saved GIF for KIC 12206313 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12206313.gif
Building 3D animation for TIC 354944123 (11/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\354944123.gif
Saved GIF for TIC 354944123 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\354944123.gif
Building 3D animation for KIC 12120307 (12/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12120307.gif
Saved GIF for KIC 12120307 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12120307.gif
Building 3D animation for TIC 256722647 (13/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\256722647.gif
Saved GIF for TIC 256722647 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\256722647.gif
Building 3D animation for KIC 12068975 (14/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12068975.gif
Saved GIF for KIC 12068975 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12068975.gif
Building 3D animation for TIC 257060897 (15/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\257060897.gif
Saved GIF for TIC 257060897 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\257060897.gif
Building 3D animation for KIC 12061969 (16/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12061969.gif
Saved GIF for KIC 12061969 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12061969.gif
Building 3D animation for TIC 289661991 (17/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\289661991.gif
Saved GIF for TIC 289661991 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\289661991.gif
Building 3D animation for KIC 12058931 (18/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12058931.gif
Saved GIF for KIC 12058931 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12058931.gif
Building 3D animation for TIC 17865622 (19/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\17865622.gif
Saved GIF for TIC 17865622 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\17865622.gif
Building 3D animation for KIC 12058204 (20/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12058204.gif
Saved GIF for KIC 12058204 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12058204.gif
Building 3D animation for TIC 428699140 (21/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\428699140.gif
Saved GIF for TIC 428699140 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\428699140.gif
Building 3D animation for KIC 12058147 (22/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12058147.gif
Saved GIF for KIC 12058147 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\12058147.gif
Building 3D animation for TIC 361343239 (23/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\361343239.gif
Saved GIF for TIC 361343239 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\361343239.gif
Building 3D animation for KIC 11963206 (24/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11963206.gif
Saved GIF for KIC 11963206 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11963206.gif
Building 3D animation for TIC 178162579 (25/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\178162579.gif
Saved GIF for TIC 178162579 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\178162579.gif
Building 3D animation for KIC 11853878 (26/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11853878.gif
Saved GIF for KIC 11853878 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11853878.gif

No data found for target "TIC 220076110".
No data found for target "TIC 220076110".
No data found for target "TIC 220076110".
No data found for target "TIC 220076110".
No data found for target "TIC 220076110".

Building 3D animation for TIC 220076110 (27/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\220076110.gif
Saved GIF for TIC 220076110 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\220076110.gif
Building 3D animation for KIC 11807274 (28/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11807274.gif
Saved GIF for KIC 11807274 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11807274.gif
Building 3D animation for TIC 258920431 (29/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\258920431.gif
Saved GIF for TIC 258920431 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\tess\258920431.gif
Building 3D animation for KIC 11764462 (30/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11764462.gif
Saved GIF for KIC 11764462 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11764462.gif
Building 3D animation for KIC 11754553 (31/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11754553.gif
Saved GIF for KIC 11754553 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11754553.gif
Building 3D animation for KIC 11720424 (32/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11720424.gif
Saved GIF for KIC 11720424 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11720424.gif
Building 3D animation for KIC 11718144 (33/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11718144.gif
Saved GIF for KIC 11718144 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11718144.gif
Building 3D animation for KIC 11656918 (34/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11656918.gif
Saved GIF for KIC 11656918 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11656918.gif
Building 3D animation for KIC 11656246 (35/35) ...
Saved animation: C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11656246.gif
Saved GIF for KIC 11656246 → C:\Roger\goals\creating\blog\NASA-Space-Apps\gifs\koi\11656246.gif